name: E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  e2e-testing:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: fast-feet-db

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22.3.0
        cache: npm
    - name: Installing dependencies
      run: npm ci
    - name: Executing tests
      run: npm run test:e2e
      env:
        JWT_KEY: "testing"
        JWT_PRIVATE_KEY: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRRFpwQk9SdVFNYk1DNVkKbk10MGlBaUpISWZqa1ZjZnNRNWdiRGZhenNXbktMZ1Jwd21jRW1NR3IwZGxIMFVndTUxTkM4bDlEQitFLzIzOQpPd1l2U3BpWVBtdWI1ZGlUQm9obmhFVnVGK2lOTjh3WElIZlZTVUVxYVR2WmFlcktVTXNrbUZQZytGajJ2R3F2CmJGNUxkRmd5NDRSL3MxT1Z4cHdsb1dQM3lRMm1wSGRMTzcvdzFVaDR3a1ZqbUpxKy94cThOc1d4TVc4T2cyeG4KWGpLZGdJMEwvTGh1MUlIVHhZdVlkTmIvM0hXMG4yUFdBNUhqOGduSXhQa1JTNUNjK0xpbWJIWnV1TitjMWwxMApkSEJ3Y1AwcUZyYWxZdnFTVTFFcVQ4b0VFb1lxbytVd0ZsS1Rid2NYWVRSaEJwdmZsdHlDOXFkMUx3N1dCeG1aCnZYTVdXNVp6QWdNQkFBRUNnZ0VBVDBmN1R2YXdBSHYxTGhkejcrL0wrREo1OS9hT1g3K09ScWExVkJKRm93WnMKd3hWdnBUaDNkVXh0ZkJNL2lkUitVVDR0ZUUxdHYvT1NYQkJmeU9OcUllOS9JS3ZDVUpDdEtOUmd2R0dlTjY4dgpPKzk2WjZwSFFFMVVYWGM5YmRTdm81V1AzS0JyTy9wWC9LNUR6VVhGQ1VpakVDZkJsNHBoZ0QzQjNsWVJrSFdsCi9JRG1SN1NsVHFzQ3daaDJtMDNVTEtlRThHOFh1RHViNXphelFOeFNsWTd3elFzcjVBZVRHajgrY2J0dUUzWDAKclpZU0ZpNFkrVTZDdXlaZXJTR2xhc2JpK05WVUJnei9EKzN3Z1RQajdNRzg5eUhzMVpneTV3T3BydXdMNkxGMAo1elVoMzdxUEpXVFdNMXh2aEpiTkZIeENZWHRnRW4rUTNIa2hVS1N4TlFLQmdRRHNJajR2eWw3UEZPd0paSjhlCm9jWldkanZ4aU1EbTNRYnBUN1NrRk1YSGg2VlRKRitGejVmOEJhL1pVWHYxYmIyNHdUcG0rVGQwb0tkRW9YMncKVGVhanpSbHVhM0pCcSs4d2lqdXozM0pzMHBucjJLdFdzbFc4V0VvS0xwenN2UUtOUjB6RWF3YmVZclREODc1QgpPVUp6UkFZT3V4WDNSWDBIRHU5djlMcTJKd0tCZ1FEcjg0cS9NOVI5VlMrQmRhd3B3ZGhFMnZNWXFIN2JSZWU0CmxrSllzVHhRU0JrbmlVTlNHWk9URDIyZHloREpkcnUvNWxvTCtQTi82a1BOelB0MC9HQVUxV3IzMkdFLzRPZGcKd3lnenYycUxnbVpnMnlGblBaRHEvcmlyUVUrTFo3VUdWM1lCTlZtNHVWbGRtYWRhSTk0MmhhazFXa01jT3dVOApMMjY3enZxNDFRS0JnRnlmdGZyekM2dDVEbmxFd2ZHM0RXQ2U4aloxS1EybHgyOC9ONkZoRUkrSzBydkJPY0w0ClFpcTJaRnIvVG50Zjk1cUFHUk9KVUVwc05oQ0N0Qld6Q1BSWm9FOGkwR2VZTkxPNmxWNmlHSFU5U3VrclRWSXQKazluVVcvNlFlRGVZa0dhd2dCbFB6aHJ2WnU2eUxuL1JJUktyclNDY0hDcXBWRGl2a0JZL1RmbmpBb0dBU2wvZwpVbGpTR0Jlcis5RE56ZlBPYWhYaUh0bXQ4d3hiK0hGVXhJUkprTHpKUVE4aGExV29rT2lDRXdUSXVkaDFZZzRJClFGSGUzMmxHcWk1ODdPbEltQWlWeVQ0cG1Xc1pSQVVBUFIrUFJCNThpdmRIMWpVdjR3TWJ6cyt0ZFRIaGUvaEIKdUN2SzlsRm1lL3lkSmVxOGRzODNBUnhNbnk5emZQOHVsb0N0dzJrQ2dZQW5DQ1N3RUN4K2VrRlFOVVRzbXN4ZgpRTm5SL1ZNS0tOTHhnVit6ZzdJYmpMdk5DRVVPeklLT0c1M0UxT3g5U3JUdkpjOFJmV0VTZE8xb044RFZ0TUtNCm4yQjNpSFlFdThTSjJkd1REZkhXZUtiOGxjREwwd0Jsd1lqMlVIVkJXc2daYVlXeGxMQ01MRGJIVU1ISTNoTUwKclFqbEZiRjF2RWtMaUg4Z095UFdKZz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"
        JWT_PUBLIC_KEY: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEyYVFUa2JrREd6QXVXSnpMZElnSQppUnlINDVGWEg3RU9ZR3czMnM3RnB5aTRFYWNKbkJKakJxOUhaUjlGSUx1ZFRRdkpmUXdmaFA5dC9Uc0dMMHFZCm1ENXJtK1hZa3dhSVo0UkZiaGZvalRmTUZ5QjMxVWxCS21rNzJXbnF5bERMSkpoVDRQaFk5cnhxcjJ4ZVMzUlkKTXVPRWY3TlRsY2FjSmFGajk4a05wcVIzU3p1LzhOVkllTUpGWTVpYXZ2OGF2RGJGc1RGdkRvTnNaMTR5bllDTgpDL3k0YnRTQjA4V0xtSFRXLzl4MXRKOWoxZ09SNC9JSnlNVDVFVXVRblBpNHBteDJicmpmbk5aZGRIUndjSEQ5CktoYTJwV0w2a2xOUktrL0tCQktHS3FQbE1CWlNrMjhIRjJFMFlRYWIzNWJjZ3ZhbmRTOE8xZ2NabWIxekZsdVcKY3dJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="
        DATABASE_URL: "postgresql://postgres:docker@localhost:5432/fast-feet-db?schema=public"
        PORT: 3333
    
